#!/usr/bin/env python
# encoding: utf8
from __future__ import (absolute_import, print_function, division, unicode_literals)

''' Simple test file for debugging and testing at the shell. To use simply
        python test.py
    or
        ./test.py
    or run 'test' in PyCharm.
'''

from crypto_enigma.machine import *


# Capture and test printing output
# USE - Replace greek letters in Haskell-generated output

def test_operation_internal(capsys):
    cfg = EnigmaConfig.config_enigma('c-β-V-II-III', 'KFIE', 'IO.QW.AG.DX.ZR', '11.19.21.16')
    cfg.print_operation_internal("XY",  mark_func=lambda c: '[' + c + ']')
    out, err = capsys.readouterr()
    assert out.split('\n')[0] ==  "     ABCDEFGHIJKLMNOPQRSTUVWXYZ "
    assert out.split('\n')[5] ==  "  4  LEYJVCNIXWPBQMDRTAKZGFUHOS   K  01  β"
    assert out.split('\n')[11] == "  P  GBCXEFAHOJKLMNIPWZSTUVQDYR          IO.QW.AG.DX.ZR"
    assert out.split('\n')[24] == "  1 [I]SHTGVBUYWDKQLZMCNAOEPFXJR         III"
    assert out.split('\n')[-2] == "P < VXWUHONEKZIRSGFYTLMQDACB[P]J"
    assert out.split('\n')[-7] == "  4 RLFOBVUXHDSANGYKMPZQW[E]JICT         β"
    cfg = EnigmaConfig.config_enigma('b-β-VIII-II-III', 'LOMQ', 'DX.ZR', '01.22.22.16')
    cfg.print_operation_internal("AB")
    out, err = capsys.readouterr()
    assert out.split('\n')[0] ==  "    ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    assert out.split('\n')[-3] ==  "  P ABCX̲̅EFGHIJKLMNOPQZSTUVWDYR         DX.ZR"
    assert out == """\
    ABCDEFGHIJKLMNOPQRSTUVWXYZ
  P ABCXEFGHIJKLMNOPQZSTUVWDYR         DX.ZR
  1 CEGIKBOQSWUYMXDHVFZJLTRPNA  Q  02  III
  2 PIWYHOEXNJSMTBRADGKUQFCVLZ  M  18  II
  3 DUPBFNCMRXOASEVJIQZWKGYHTL  O  20  VIII
  4 QFBSGIPZOVUJWDHATNYKRCXMLE  L  12  β
  R ENKQAUYWJICOPBLMDXZVFTHRGS         b
  4 PCVNZBEOFLTYXRIGAUDQKJMWSH         β
  3 LDGANEVXQPUZHFKCRIMYBOTJWS         VIII
  2 PNWQGVREBJSYLIFAUOKMTXCHDZ         II
  1 ZFAOBRCPDTEUMYGXHWIVKQJNLS         III
  P ABCXEFGHIJKLMNOPQZSTUVWDYR         DX.ZR
    KISPJWRVBEAQYTZDLGCNXHFUMO

A > A̲̅BCDEFGHIJKLMNOPQRSTUVWXYZ
  P A̲̅BCXEFGHIJKLMNOPQZSTUVWDYR         DX.ZR
  1 D̲̅FHJANPRVTXLWCGUEYIKSQOMZB  R  03  III
  2 PIWY̲̅HOEXNJSMTBRADGKUQFCVLZ  M  18  II
  3 DUPBFNCMRXOASEVJIQZWKGYHT̲̅L  O  20  VIII
  4 QFBSGIPZOVUJWDHATNYK̲̅RCXMLE  L  12  β
  R ENKQAUYWJIC̲̅OPBLMDXZVFTHRGS         b
  4 PCV̲̅NZBEOFLTYXRIGAUDQKJMWSH         β
  3 LDGANEVXQPUZHFKCRIMYBO̲̅TJWS         VIII
  2 PNWQGVREBJSYLIF̲̅AUOKMTXCHDZ         II
  1 EZNAQB̲̅OCSDTLXFWGVHUJPIMKRY         III
  P AB̲̅CXEFGHIJKLMNOPQZSTUVWDYR         DX.ZR
B < B̲̅AGFWDCRZVXSTPYNUHLMQJEKOI

B > AB̲̅CDEFGHIJKLMNOPQRSTUVWXYZ
  P AB̲̅CXEFGHIJKLMNOPQZSTUVWDYR         DX.ZR
  1 EG̲̅IZMOQUSWKVBFTDXHJRPNLYAC  S  04  III
  2 PIWYHOE̲̅XNJSMTBRADGKUQFCVLZ  M  18  II
  3 DUPBF̲̅NCMRXOASEVJIQZWKGYHTL  O  20  VIII
  4 QFBSGI̲̅PZOVUJWDHATNYKRCXMLE  L  12  β
  R ENKQAUYWJ̲̅ICOPBLMDXZVFTHRGS         b
  4 PCVNZBEOFL̲̅TYXRIGAUDQKJMWSH         β
  3 LDGANEVXQPUZ̲̅HFKCRIMYBOTJWS         VIII
  2 PNWQGVREBJSYLIFAUOKMTXCHDZ̲̅         II
  1 YMZPANBRCSKWEVFUGTIOHLJQXD̲̅         III
  P ABCX̲̅EFGHIJKLMNOPQZSTUVWDYR         DX.ZR
X < IX̲̅WLVYORAKJDTPGNSHQMZECBFU
"""


def test_operation_single(capsys):
    cfg = EnigmaConfig.config_enigma('C-I-II-III', 'ABC', 'IO.AG.DM.ZR', '19.05.06')
    cfg.print_operation("NATURE", format='single')
    out, err = capsys.readouterr()
    assert out == """\
    FUQMGAEKOXHSDZIWCTLRBYPJVN  ABC  09 24 24
N > NJVKRPWMQBDZHA̲̅YFIEUXSCGTOL  ABD  09 24 25
A > J̲̅HDCFEZBLATIXURYWOVKNSQMPG  ABE  09 24 26
T > BANJHKTERDFSWCYZUILG̲̅QXMVOP  ABF  09 24 01
U > LJQOMRIWGBPAEUDKCFVXN̲̅SHTZY  ABG  09 24 02
R > MFPQRBNVOYLKAGICDE̲̅TSXHZUJW  ABH  09 24 03
E > TLKYO̲̅XJZMGCBIVERWPUASNQFDH  ABI  09 24 04
"""
    cfg = EnigmaConfig.config_enigma('B-I-IV-III', 'PKD', 'LE.IO.AG.DM.ZR', '11.05.07')
    cfg.print_operation("THE MAN IN THE HIGH CASTLE", format='single', mark_func=lambda c: '(' + c + ')')
    out, err = capsys.readouterr()
    assert out == """\
     UIPXSRVMBTYQHZWCLFEJAGODKN   PKD  06 07 24
T > MZXSFEPYQVTRAUWGILD(K)NJOCHB  PKE  06 07 25
H > CRAWYPJ(I)HGTSOUMFVBLKNQDZEX  PKF  06 07 26
E > ORFU(L)CTXJIQEWZAVKBYGDPMHSN  PKG  06 07 01
M > IDHBVRWCAYPS(N)MXKTFLQZEGOJU  PKH  06 07 02
A > (U)EPFBDWNVZSROHMCXLKYAIGQTJ  PKI  06 07 03
N > BAQYSPLZXVMGK(W)UFCTEROJNIDH  PKJ  06 07 04
I > CKAUYNMI(H)OBPGFJLSTQRDXZVEW  PKK  06 07 05
N > GOKYLZAQUWCER(X)BTHMVPISJNDF  PKL  06 07 06
T > JURXPOMNZALKGHFEYCW(V)BTSDQI  PKM  06 07 07
H > MEYVBKO(X)QWFNALGUIZTSPDJHCR  PKN  06 07 08
E > ZFEL(C)BTMNXSDHIWVUYKGQPOJRA  PKO  06 07 09
H > IDLBVZH(G)ARWCYQTSNJPOXEKUMF  PKP  06 07 10
I > ZXWUQYOP(J)IVMLTGHESRNDKCBFA  PKQ  06 07 11
G > NIVZHY(J)EBGUTSAQXOWMLKCRPFD  PKR  06 07 12
H > XJDCUTL(V)MBSGIPQNOZKFEHYAWR  PKS  06 07 13
C > ZK(U)GNSDYWQBMLEXTJVFPCRIOHA  PKT  06 07 14
A > (D)OXATJRPKFINZLBHWGUESYQCVM  PKU  06 07 15
S > VYPOURILGSXHTWDCZF(J)MEANKBQ  PKV  06 07 16
T > MXKHGTEDUWCRASPOZLN(F)IYJBVQ  PLW  06 08 17
L > RSQPIWVKEUH(Z)XYTDCABOJGFMNL  PLX  06 08 18
E > OSKZ(L)VMTRYCEGUAWXIBHNFPQJD  PLY  06 08 19
"""


def test_operation_windows(capsys):
    cfg = EnigmaConfig.config_enigma('B-I-IV-III', 'PKD', 'LE.IO.AG.DM.ZR', '11.05.07')
    cfg.print_operation("THE MAN IN THE HIGH CASTLE", format='windows', show_encoding=True, show_step=True)
    out, err = capsys.readouterr()
    assert out == """\
0000  PKD
0001  PKE  T > K
0002  PKF  H > I
0003  PKG  E > L
0004  PKH  M > N
0005  PKI  A > U
0006  PKJ  N > W
0007  PKK  I > H
0008  PKL  N > X
0009  PKM  T > V
0010  PKN  H > X
0011  PKO  E > C
0012  PKP  H > G
0013  PKQ  I > J
0014  PKR  G > J
0015  PKS  H > V
0016  PKT  C > U
0017  PKU  A > D
0018  PKV  S > J
0019  PLW  T > F
0020  PLX  L > Z
0021  PLY  E > L
"""


def test_encoding(capsys):
    cfg = EnigmaConfig.config_enigma('B-β-V-IV-III', 'ZZZZ', 'LE.IO.AG.DM.ZR', '11.11.11.11')
    cfg.print_encoding("THE MAN IN THE HIGH CASTLE")
    out, err = capsys.readouterr()
    assert out == """\
MTPP XOGC IFXU YSEE TXEI Y
"""
    cfg = EnigmaConfig.config_enigma('c-β-V-VI-VIII', EnigmaConfig.config_enigma('c-β-V-VI-VIII', 'NAEM', 'AE.BF.CM.DQ.HU.JN.LX.PR.SZ.VW', '05.16.05.12').enigma_encoding('QEOB'), 'AE.BF.CM.DQ.HU.JN.LX.PR.SZ.VW', '05.16.05.12')
    msg = 'KRKR ALLE XX FOLGENDES IST SOFORT BEKANNTZUGEBEN XX ICH HABE FOLGELNBE BEFEHL ERHALTEN XX J ANSTERLE DES BISHERIGXN REICHSMARSCHALLS J GOERING J SETZT DER FUEHRER SIE Y HVRR GRZSSADMIRAL Y ALS SEINEN NACHFOLGER EIN X SCHRIFTLSCHE VOLLMACHT UNTERWEGS X ABSOFORT SOLLEN SIE SAEMTLICHE MASSNAHMEN VERFUEGEN Y DIE SICH AUS DER GEGENWAERTIGEN LAGE ERGEBEN X GEZ X REICHSLEITEI KK TULPE KK J BORMANN J XX OB.D.MMM DURNH FKST.KOM.ADM.UUU BOOIE.KP'
    cfg.print_encoding(msg)
    out, err = capsys.readouterr()
    assert out == "LANO TCTO UARB BFPM HPHG CZXT DYGA HGUF XGEW KBLK GJWL QXXT \nGPJJ AVTO CKZF SLPP QIHZ FXOE BWII EKFZ LCLO AQJU LJOY HSSM \nBBGW HZAN VOII PYRB RTDJ QDJJ OQKC XWDN BBTY VXLY TAPG VEAT \nXSON PNYN QFUD BBHH VWEP YEYD OHNL XKZD NWRH DUWU JUMW WVII \nWZXI VIUQ DRHY MNCY EFUA PNHO TKHK GDNP SAKN UAGH JZSM JBMH \nVTRE QEDG XHLZ WIFU SKDQ VELN MIMI THBH DBWV HDFY HJOQ IHOR \nTDJD BWXE MEAY XGYQ XOHF DMYU XXNO JAZR SGHP LWML RECW WUTL \nRTTV LBHY OORG LGOW UXNX HMHY FAAC QEKT HSJW\n"
